name: dev-beanstalk-springboot-deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #JDK Setting
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      #Create dotenv file
      - name: Make env properties
        run: |
          touch ./src/main/resources/application-dev.yml
          echo "$ENV_PROPERTIES_DEV" > ./src/main/resources/application-dev.yml
          touch ./src/main/resources/tikitaka-fcm.json
          echo "$FCM_JSON" > ./src/main/resources/tikitaka-fcm.json
        env:
          ENV_PROPERTIES_DEV: ${{ secrets.ENV_PROPERTIES_DEV }}
          FCM_JSON: ${{ secrets.FCM_JSON }}

      #Grant gradlew Permission
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=$"
        shell: bash

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          application_name: ${{ secrets.EB_APPLICATION_NAME_DEV }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME_DEV }}
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
